"""empty message

Revision ID: 1fbe29cd6745
Revises: 98fba4090cc7
Create Date: 2018-05-03 12:49:39.992821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbe29cd6745'
down_revision = '98fba4090cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined')
    # ### end Alembic commands ###
