"""empty message

Revision ID: 98fba4090cc7
Revises: 4269e5f12133
Create Date: 2018-05-03 12:45:38.215082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fba4090cc7'
down_revision = '4269e5f12133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_you', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('occupation', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'occupation')
    op.drop_column('user', 'about_you')
    # ### end Alembic commands ###
